app = 'weather-patrol'
primary_region = 'ord'

[build]
  builder = "heroku/builder:22"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  API_KEY = "secret_api_key"
  FRONTEND_URL = "https://weather-patrol.fly.dev"
  LOG_LEVEL = "info"
  VITE_API_BASE_URL = "https://weather-patrol.fly.dev/api"
  VITE_LOG_LEVEL = "warn"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 3000        # Port Node.js backend listens on
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data_storage"
  destination = "/file-server/data"
